### ISSUE TITLE
Error in estimateCellCounts

### ISSUE THREAD

**Issue by MeganBreitbach** [kasperdanielhansen/minfi#87]
I get an error regarding the slot names for the RGset when implementing my code to determine cell counts from methylEPIC data. Could anyone help me out here?

##Read in data
targets<-read.metharray.sheet(base = "~/Documents/IDATS", pattern = "csv$", ignore.case = TRUE,
                              recursive = TRUE, verbose = TRUE )

path<-"~/Documents/IDATS"
RGset<-read.metharray.exp(base = path, targets = targets, extended = FALSE,recursive = FALSE, verbose = FALSE, force = FALSE)
pData<- pData(RGset)
pData$Sample_Name <- as.character(pData$Sample_Name)
pData(RGset) <- pData

require(FlowSorted.Blood.450k)

cellCounts <- estimateCellCounts(RGset)

Error in colData(referenceRGset) : 
  no slot of name "colData" for this object of class "RGChannelSet"
Error in nrow(x@elementMetadata) : 
  no slot of name "elementMetadata" for this object of class "RGChannelSet"

**Comment by kasperdanielhansen** [comment]
I think you're using the devel version of minfi, right?  I think this is
because we have changed the underlying class structures.  We have updated
the minfiData / minfiDataEPIC packages to support this, but we have not yet
updated the FlowSorted.XX packages (well, I kind of forgot to be honest).
You can update "old" objects to the new format by running updateObject().

Unfortunately, due to how estimateCellCounts is coded, you need to update
the data in the package; it cannot be overridden by a user.  So you'll have
to wait until we fix this, which I hope will happen by the end of this week.

**Comment by MeganBreitbach** [comment]
So you are saying, before I run cellCounts <- estimateCellCounts(RGset) 

I should run RGSet<- updateObject(RGset) ??

I tried this, and it did not work.

**Comment by kasperdanielhansen** [comment]
No, I'm saying that I need to update the reference data stored in the
FlowCell.XX package(s) and you can only fix it by updating the package.

**Comment by MeganBreitbach** [comment]
I reinstalled the FlowSorted.Blood.450k, minfi, and minfiData, and ran updateObject(FlowSorted.Blood.450k) prior to calling cellCounts <- estimateCellCounts(RGset) and still get the same error

**Comment by kasperdanielhansen** [comment]
I updated the reference packages a long time ago, so it should have been working for a while.  Closing.
